/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { AppNavProps } from 'src/types';

const AppNav1: any = styled('div')(({ theme }: any) => ({
  color: theme.palette['colors']['grey']['300'],
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `center`,
  alignItems: `flex-start`,
  height: 'auto',
}));

function AppNav(props: AppNavProps): JSX.Element {
  return <AppNav1 className={props.className}></AppNav1>;
}

export default AppNav;
