/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';

type EntityType = {
  value: string;
  text: string;
}

type TaxIdType = {
  value: string;
  text: string;
}

type ForeignInvestorType = {
  value: string;
  text: string;
}

type AccreditationType = {
  value: string;
  text: string;
}

type FormEntityProps = {
  className?: string;
}

type FormEntityData = {
  entityTypes: EntityType[];
  taxIdType: TaxIdType[];
  foreignInvestorType: ForeignInvestorType[];
  accreditationTypes: AccreditationType[];
}

const useFormEntity = () => {
  let data: FormEntityData = {
    entityTypes: [
      { value: 'entityType1', text: 'Entity Type 1' },
      { value: 'entityType2', text: 'Entity Type 2' },
      { value: 'entityType3', text: 'Entity Type 3' }
    ],
    taxIdType: [
      { value: 'taxIdType1', text: 'Tad ID Type 1' },
      { value: 'taxIdType2', text: 'Tax ID Type 2' },
      { value: 'taxIdType3', text: 'Tax ID Type 3' }
    ],
    foreignInvestorType: [],
    accreditationTypes: []
  };
  const getEntity = (): any => {
    return "Entity";
  };

  let fns: any = { getEntity };
  return { data, fns };
};

export default useFormEntity;