/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { TestCardProps } from 'src/types';
const useTestCard = (props: TestCardProps) => {
  let data: any = {};
  const handleButtonClick = (): any => {};

  let fns: any = { handleButtonClick };
  return { data, fns };
};

export default useTestCard;
