/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { BreadcrumbsProps } from 'src/types';

const Breadcrumbs1: any = styled('div')(({ theme }: any) => ({
  color: theme.palette['primary']['main'],
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  height: 'auto',
}));

function Breadcrumbs(props: BreadcrumbsProps): JSX.Element {
  return <Breadcrumbs1 className={props.className}></Breadcrumbs1>;
}

export default Breadcrumbs;
