/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/
























export interface PageParentProps {
  className?: any;
}














export interface FormEntityProps {
  className?: any;
}








export interface HeaderProps {
  className?: any;
}















export interface SampleCardProps {
  className?: any;
  metadata: any;
}
























export interface SampleCardGridProps {
  className?: any;
}
























export interface TestCardProps {
  className?: any;
  prop1: any;
}
























export interface Form1Props {
  className?: any;
  prop1: any;
}
























export interface FormEntityOldProps {
  className?: any;
}


















export interface MyTabProps {
  className?: any;
}










